name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Cypress tests
        uses: cypress-io/github-action@v7
        with:
          command: xvfb-run -a --server-args="-screen 0 1920x1080x24" npx cypress run --browser electron --headed --config viewportWidth=1920,viewportHeight=1080